server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///D:\\WorkSpaces\\git-local-repo
          default-label: master
