server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kadun1/spring-cloud-config-study.git
          default-label: master
